include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_final_parameters
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - conditional_uri_does_not_exist
    - directives_ordering
    - eol_at_end_of_file
    - literal_only_boolean_expressions
    - noop_primitive_operations
    - omit_local_variable_types
    - one_member_abstracts
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_colored_box
    - use_enums
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/gen/assets.gen.dart"
    - "lib/l10n/gen/*"
  # strong-mode:
  #   TODO: consider disabling
  #   implicit-dynamic: false
