const String mockTextPostJson = r'''
{
    "post": {
      "id": 440073,
      "name": "I need to survive for 3 days without pooping, and eating as little as possible. I can pee, but not very often. It can't take up too much space. What food do I pack?",
      "url": null,
      "body": "Please don't ask why I need this.\n\nIt would be great if the food also made me sweat less.\n\nIt has to be something I can easily find.\n\n\nEDITS FOR CLARIFICATION:\n\n- I am not planning on partaking in any illegal activities.\n\n- I do not condone the use of illegal substances and am not planning on smuggling anything anywhere.\n\n- I am not going on a hiking trip or mailing myself anywhere.\n\n- I will be staying in a tent (not a small one; a huge with with air conditioning and everything). I will be traveling for five days, returning to my current location on day 3 and traveling again on the last two days. I will not poop on the first three days (hopefully).\n\n- Clean toilets with all the expected facilities **will** be available to me. I am not going to poop for reasons that I wish to keep to myself.\n\n- If it gets bad, like really bad, like a-piece-of-poop-is-literally-halfway-out-my-ass bad, I will use the toilets.\n\n\nPlease stop asking because I am not telling anyone the reason.",
      "creator_id": 94330,
      "community_id": 38,
      "removed": false,
      "locked": false,
      "published": "2023-06-22T21:01:34.352989",
      "updated": "2023-06-23T01:23:11.476767",
      "deleted": false,
      "nsfw": false,
      "embed_title": null,
      "embed_description": null,
      "embed_video_url": null,
      "thumbnail_url": null,
      "ap_id": "https://lemmy.world/post/440073",
      "local": true,
      "language_id": 37,
      "featured_community": false,
      "featured_local": false,
      "instance_host": "https://lemmy.world"
    },
    "creator": {
      "id": 94330,
      "name": "mizu6079",
      "display_name": "mizu",
      "avatar": "https://lemmy.world/pictrs/image/8f41f371-09ec-4952-bdbe-6bc1b338f2a3.jpeg",
      "banned": false,
      "published": "2023-06-13T15:50:25.833352",
      "updated": null,
      "actor_id": "https://lemmy.world/u/mizu6079",
      "bio": null,
      "local": true,
      "banner": null,
      "deleted": false,
      "inbox_url": "https://lemmy.world/u/mizu6079/inbox",
      "shared_inbox_url": "https://lemmy.world/inbox",
      "matrix_user_id": "@mizu6079:matrix.org",
      "admin": false,
      "bot_account": false,
      "ban_expires": null,
      "instance_id": 1,
      "instance_host": "https://lemmy.world"
    },
    "community": {
      "id": 38,
      "name": "asklemmy",
      "title": "asklemmy",
      "description": "A loosely moderated place to ask open ended questions\n\nIf your post is\n\n1. Open ended \n2. Not offensive (At this point, I do not have the bandwidth to moderate partisan political discussions)\n3. **Not regarding lemmy support** ([!lemmy_support@lemmy.ml](https://lemmy.ml/c/lemmy_support) )\n4. not ad nauseam inducing (please make sure its a question that would be new to most members)\n5. [An actual topic of discussion](https://lemmy.ml/post/1239589)\n\nit’s welcome here!",
      "removed": false,
      "published": "2019-04-25T04:58:33.886275",
      "updated": "2023-06-14T00:05:37.871496",
      "deleted": false,
      "nsfw": false,
      "actor_id": "https://lemmy.ml/c/asklemmy",
      "local": false,
      "icon": "https://lemmy.ml/pictrs/image/UsuGsKF2fl.png",
      "banner": "https://lemmy.ml/pictrs/image/XKAjSZCX2P.png",
      "hidden": false,
      "posting_restricted_to_mods": false,
      "instance_id": 3,
      "instance_host": "https://lemmy.world"
    },
    "creator_banned_from_community": false,
    "counts": {
      "id": 121974,
      "post_id": 440073,
      "comments": 845,
      "score": 2057,
      "upvotes": 2139,
      "downvotes": 82,
      "published": "2023-06-22T21:01:34.352989",
      "newest_comment_time_necro": "2023-06-24T20:57:15.835538",
      "newest_comment_time": "2023-06-27T03:56:01.144687",
      "featured_community": false,
      "featured_local": false,
      "hot_rank": 7,
      "hot_rank_active": 21,
      "instance_host": "https://lemmy.world"
    },
    "subscribed": "NotSubscribed",
    "saved": false,
    "read": false,
    "creator_blocked": false,
    "my_vote": null,
    "unread_comments": 845,
    "instance_host": "https://lemmy.world"
  }
''';

const String mockMediaPost = r'''
{
    "post": {
      "id": 482303,
      "name": "This is a test post. Don't upvote.",
      "url": "https://archives.bulbagarden.net/media/upload/3/3a/0039Jigglypuff.png",
      "body": "(__)_) <<>> (_(__)",
      "creator_id": 379489,
      "community_id": 1994,
      "removed": false,
      "locked": false,
      "published": "2023-06-23T20:16:43.707718",
      "updated": null,
      "deleted": false,
      "nsfw": false,
      "embed_title": null,
      "embed_description": null,
      "embed_video_url": null,
      "thumbnail_url": null,
      "ap_id": "https://lemmy.world/post/482303",
      "local": true,
      "language_id": 37,
      "featured_community": false,
      "featured_local": false,
      "instance_host": "https://lemmy.world"
    },
    "creator": {
      "id": 379489,
      "name": "B0T",
      "display_name": "B0T",
      "avatar": "https://lemmy.world/pictrs/image/925ddf0c-1975-456f-996a-724d89d61940.png",
      "banned": false,
      "published": "2023-06-23T20:03:04.375182",
      "updated": null,
      "actor_id": "https://lemmy.world/u/B0T",
      "bio": "Beep boop, I'm called B0T, but I'm actually a human.",
      "local": true,
      "banner": "https://lemmy.world/pictrs/image/1ce3acdf-b755-4225-b676-975bff0042cd.jpeg",
      "deleted": false,
      "inbox_url": "https://lemmy.world/u/B0T/inbox",
      "shared_inbox_url": "https://lemmy.world/inbox",
      "matrix_user_id": null,
      "admin": false,
      "bot_account": false,
      "ban_expires": null,
      "instance_id": 1,
      "instance_host": "https://lemmy.world"
    },
    "community": {
      "id": 1994,
      "name": "lemmyshitpost",
      "title": "Lemmy Shitpost",
      "description": "Welcome to Lemmy Shitpost. Here you can shitpost to your hearts content.\n\nAnything and everything goes. Memes, Jokes, Vents and Banter. Though we still have to comply with lemmy.world instance rules. So behave!\n\n...\n\n**Rules:**\n\n**1.** Be Respectful\n\n**2.** No Illegal Content\n\n**3.** No Spam\n\n**4.** No Porn/Sexually Explicit \nContent\n\n**5.** No Enciting Harassment, \nBrigading, Doxxing or Witch Hunts\n\n**6.** NSFW should be behind NSFW tags.\n\n...\n\nIf you see content that is a breach of the rules, please flag and report the comment and a moderator will take action where they can.\n\n...\n\n**Also check out:**\n\n**Partnered Communities:**\n\n1.[Lemmy Review](/c/lemmyreview@lemmy.world)\n\n2.[Mildly Infuriating](/c/mildlyinfuriating@lemmy.world)\n\n3.[Lemmy Be Wholesome](/c/lemmybewholesome@lemmy.world)\n\n4.[No Stupid Questions](/c/nostupidquestions@lemmy.world)\n\n5.[You Should Know](/c/youshouldknow@lemmy.world)\n\n6.[Comedy Heaven](/c/comedyheaven@lemm.world)\n\n7.[Credible Defense](/c/credibledefense@sh.itjust.works)\n\n\n...\nReach out to [LillianVS](/u/LillianVS@lemmy.world) for inclusion on the sidebar. \n\n*All communities included on the sidebar are to be made in compliance with the instance rules.*",
      "removed": false,
      "published": "2023-06-10T16:30:55.861489",
      "updated": "2023-06-23T01:07:06.547485",
      "deleted": false,
      "nsfw": false,
      "actor_id": "https://lemmy.world/c/lemmyshitpost",
      "local": true,
      "icon": "https://lemmy.world/pictrs/image/d82718c7-5579-4676-8e2e-97b4188f10d3.png",
      "banner": "https://lemmy.world/pictrs/image/7f4a91de-49a1-4f76-a257-afab586d9abf.png",
      "hidden": false,
      "posting_restricted_to_mods": false,
      "instance_id": 1,
      "instance_host": "https://lemmy.world"
    },
    "creator_banned_from_community": false,
    "counts": {
      "id": 131500,
      "post_id": 482303,
      "comments": 79,
      "score": 1848,
      "upvotes": 2017,
      "downvotes": 169,
      "published": "2023-06-23T20:16:43.707718",
      "newest_comment_time_necro": "2023-06-25T07:03:18.455706",
      "newest_comment_time": "2023-06-25T07:03:18.455706",
      "featured_community": false,
      "featured_local": false,
      "hot_rank": 11,
      "hot_rank_active": 29,
      "instance_host": "https://lemmy.world"
    },
    "subscribed": "NotSubscribed",
    "saved": false,
    "read": false,
    "creator_blocked": false,
    "my_vote": null,
    "unread_comments": 79,
    "instance_host": "https://lemmy.world"
  }
''';

const String mockLinkPost = r'''
{
    "post": {
      "id": 206930,
      "name": "Reddit: open /r/pics or else. Mods: OK but you didn't say how",
      "url": "https://archive.ph/xUE1M",
      "body": "I honestly don't know if this is allowed here but I thought this is malicious compliance at its finest.\n\nIf you don't want to drive traffic there I'll repost what the mods posted below:\n\n\n**POLL: Decide on the future of /r/Pics!**\n\nHello, /r/Pics subscribers!\n\nBoy, what a whacky time we've all had lately, huh? Reddit decided to kill off third-party applications, a protest got planned (and possibly exploited by bad actors), the site showed up in the news, various communities started opening back up, others decided to stay inaccessible, and then the CEO of Reddit implied that a bunch of moderators would be removed from their positions!\n\nCrazy, right?\n\nAnyway, we – the so-called \"landed gentry\" – definitely want to comply with the wishes of the \"royal court,\" and they've told us that we need to run the subreddit in the way that its members want. To that end, we figured that the only reasonable thing to do was directly ask how you'd like things to progress from here.\n\nWhich of the following should we do?\n\n1. Return to normal operations\n\n2. Only allow images of John Oliver looking sexy\nTo be clear, if people choose the second option, screen-grabs from videos will be allowed (provided that there aren't any visible logos, inserted graphics, or other digital elements present). You could – if you wanted to – look through episodes of Last Week Tonight on YouTube, find moments featuring John Oliver at his sexiest, then post images of those moments here.\n\nIt's entirely up to you! Whatever the /r/Pics community decides is best, we'll respect!\n\nVote, friends! Vote now!\n\n(You can vote by upvoting either of the comments in the thread below.)\n\n**Voting has now closed.**\n\nOur final tally is as follows:\n\nReturn to normal operations: -2,329 votes\n\nOnly allow images of John Oliver looking sexy: 37,331 votes\n\nIt would seem that the community has spoken!\n\n**Henceforth, /r/Pics will only allow images of John Oliver looking sexy.**\n\n(Said images must adhere to all of the community's other rules, including those mandated by Reddit.)\n\nHappy posting!",
      "creator_id": 184655,
      "community_id": 8195,
      "removed": false,
      "locked": false,
      "published": "2023-06-17T00:29:24.621358",
      "updated": "2023-06-17T04:07:17.919920",
      "deleted": false,
      "nsfw": false,
      "embed_title": "POLL: Decide on the future of /r/Pics!",
      "embed_description": "Hello, /r/Pics subscribers! Boy, what a whacky time we've all had lately, huh? Reddit decided to kill off third-party applications, a protest got...",
      "embed_video_url": null,
      "thumbnail_url": "https://lemmy.dbzer0.com/pictrs/image/c8e2f5d6-7913-42bd-bddb-48619a38ab7b.png",
      "ap_id": "https://lemmy.dbzer0.com/post/35819",
      "local": false,
      "language_id": 37,
      "featured_community": false,
      "featured_local": false,
      "instance_host": "https://lemmy.world"
    },
    "creator": {
      "id": 184655,
      "name": "LenticularTorsion",
      "display_name": null,
      "avatar": null,
      "banned": false,
      "published": "2023-06-17T00:02:19.237480",
      "updated": null,
      "actor_id": "https://lemmy.dbzer0.com/u/LenticularTorsion",
      "bio": null,
      "local": false,
      "banner": null,
      "deleted": false,
      "inbox_url": "https://lemmy.dbzer0.com/u/LenticularTorsion/inbox",
      "shared_inbox_url": "https://lemmy.dbzer0.com/inbox",
      "matrix_user_id": null,
      "admin": false,
      "bot_account": false,
      "ban_expires": null,
      "instance_id": 723,
      "instance_host": "https://lemmy.world"
    },
    "community": {
      "id": 8195,
      "name": "maliciouscompliance",
      "title": "Malicious Compliance",
      "description": "People conforming to the letter, but not the spirit, of a request. For now, this includes text posts, images, videos and links. Please ensure that the “malicious compliance” aspect is apparent - if you’re making a text post, be sure to explain this part; if it’s an image/video/link, use the “Body” field to elaborate.\n\n======\n\n- We ENCOURAGE posts about events that happened to you, or someone you know.\n\n- We ACCEPT (for now) reposts of good malicious compliance stories (from other platforms) which did not happen to you or someone you knew. **Please use a [REPOST] tag in such situations.**\n\n- We DO NOT ALLOW fiction, or posts that break site-wide rules.\n\n======\n\nAlso check out the following communities:\n\n[!fakehistoryporn@lemmy.world](/c/fakehistoryporn@lemmy.world)\n[!unethicallifeprotips@lemmy.world](/c/unethicallifeprotips@lemmy.world)\n\n",
      "removed": false,
      "published": "2023-06-14T09:06:00.353475",
      "updated": "2023-06-21T01:06:14.375314",
      "deleted": false,
      "nsfw": false,
      "actor_id": "https://lemmy.world/c/maliciouscompliance",
      "local": true,
      "icon": "https://lemmy.world/pictrs/image/94450a36-7ffd-4f86-826b-ca02e9abb3eb.png",
      "banner": "https://lemmy.world/pictrs/image/2d2d9622-be3d-4a0e-8e4d-1053e0181921.png",
      "hidden": false,
      "posting_restricted_to_mods": false,
      "instance_id": 1,
      "instance_host": "https://lemmy.world"
    },
    "creator_banned_from_community": false,
    "counts": {
      "id": 71468,
      "post_id": 206930,
      "comments": 223,
      "score": 1451,
      "upvotes": 1462,
      "downvotes": 11,
      "published": "2023-06-17T00:29:24.621358",
      "newest_comment_time_necro": "2023-06-18T17:27:17.621116",
      "newest_comment_time": "2023-06-23T21:02:47.167080",
      "featured_community": false,
      "featured_local": false,
      "hot_rank": 1,
      "hot_rank_active": 2,
      "instance_host": "https://lemmy.world"
    },
    "subscribed": "NotSubscribed",
    "saved": false,
    "read": false,
    "creator_blocked": false,
    "my_vote": null,
    "unread_comments": 223,
    "instance_host": "https://lemmy.world"
  }
''';
