const String mockComentTree = r'''
{
    "post": {
      "id": 440073,
      "name": "I need to survive for 3 days without pooping, and eating as little as possible. I can pee, but not very often. It can't take up too much space. What food do I pack?",
      "url": null,
      "body": "Please don't ask why I need this.\n\nIt would be great if the food also made me sweat less.\n\nIt has to be something I can easily find.\n\n\nEDITS FOR CLARIFICATION:\n\n- I am not planning on partaking in any illegal activities.\n\n- I do not condone the use of illegal substances and am not planning on smuggling anything anywhere.\n\n- I am not going on a hiking trip or mailing myself anywhere.\n\n- I will be staying in a tent (not a small one; a huge with with air conditioning and everything). I will be traveling for five days, returning to my current location on day 3 and traveling again on the last two days. I will not poop on the first three days (hopefully).\n\n- Clean toilets with all the expected facilities **will** be available to me. I am not going to poop for reasons that I wish to keep to myself.\n\n- If it gets bad, like really bad, like a-piece-of-poop-is-literally-halfway-out-my-ass bad, I will use the toilets.\n\n\nPlease stop asking because I am not telling anyone the reason.",
      "creator_id": 94330,
      "community_id": 38,
      "removed": false,
      "locked": false,
      "published": "2023-06-22T21:01:34.352989",
      "updated": "2023-06-23T01:23:11.476767",
      "deleted": false,
      "nsfw": false,
      "embed_title": null,
      "embed_description": null,
      "embed_video_url": null,
      "thumbnail_url": null,
      "ap_id": "https://lemmy.world/post/440073",
      "local": true,
      "language_id": 37,
      "featured_community": false,
      "featured_local": false,
      "instance_host": "https://lemmy.world"
    },
    "creator": {
      "id": 94330,
      "name": "mizu6079",
      "display_name": "mizu",
      "avatar": "https://lemmy.world/pictrs/image/8f41f371-09ec-4952-bdbe-6bc1b338f2a3.jpeg",
      "banned": false,
      "published": "2023-06-13T15:50:25.833352",
      "updated": null,
      "actor_id": "https://lemmy.world/u/mizu6079",
      "bio": null,
      "local": true,
      "banner": null,
      "deleted": false,
      "inbox_url": "https://lemmy.world/u/mizu6079/inbox",
      "shared_inbox_url": "https://lemmy.world/inbox",
      "matrix_user_id": "@mizu6079:matrix.org",
      "admin": false,
      "bot_account": false,
      "ban_expires": null,
      "instance_id": 1,
      "instance_host": "https://lemmy.world"
    },
    "community": {
      "id": 38,
      "name": "asklemmy",
      "title": "asklemmy",
      "description": "A loosely moderated place to ask open ended questions\n\nIf your post is\n\n1. Open ended \n2. Not offensive (At this point, I do not have the bandwidth to moderate partisan political discussions)\n3. **Not regarding lemmy support** ([!lemmy_support@lemmy.ml](https://lemmy.ml/c/lemmy_support) )\n4. not ad nauseam inducing (please make sure its a question that would be new to most members)\n5. [An actual topic of discussion](https://lemmy.ml/post/1239589)\n\nit’s welcome here!",
      "removed": false,
      "published": "2019-04-25T04:58:33.886275",
      "updated": "2023-06-14T00:05:37.871496",
      "deleted": false,
      "nsfw": false,
      "actor_id": "https://lemmy.ml/c/asklemmy",
      "local": false,
      "icon": "https://lemmy.ml/pictrs/image/UsuGsKF2fl.png",
      "banner": "https://lemmy.ml/pictrs/image/XKAjSZCX2P.png",
      "hidden": false,
      "posting_restricted_to_mods": false,
      "instance_id": 3,
      "instance_host": "https://lemmy.world"
    },
    "creator_banned_from_community": false,
    "counts": {
      "id": 121974,
      "post_id": 440073,
      "comments": 845,
      "score": 2057,
      "upvotes": 2139,
      "downvotes": 82,
      "published": "2023-06-22T21:01:34.352989",
      "newest_comment_time_necro": "2023-06-24T20:57:15.835538",
      "newest_comment_time": "2023-06-27T03:56:01.144687",
      "featured_community": false,
      "featured_local": false,
      "hot_rank": 7,
      "hot_rank_active": 21,
      "instance_host": "https://lemmy.world"
    },
    "subscribed": "NotSubscribed",
    "saved": false,
    "read": false,
    "creator_blocked": false,
    "my_vote": null,
    "unread_comments": 845,
    "instance_host": "https://lemmy.world"
  }
''';
